services:  
  node:
    image: grpc-node
    volumes:
      - ./:/home/node/app
    container_name: node-server
    command: "npm start"
    depends_on:
      - grpc-server
      - mongodb
      - redis

  grpc-server:    
    image: grpc-server  
    container_name: grpc-server
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  redis:    
    image: redis/redis-stack:latest
    container_name: redis-stack    
    ports:      
      - "${REDIS_INSIGHT_PORT}:8001" # This port is use for UI Redis
    environment:      
      - REDIS_ARGS=--requirepass ${REDIS_PASS}
    volumes:
      - ./redis-data:/data
    restart: unless-stopped

  nginx:    
    image: nginx:latest    
    container_name: nginx    
    environment:
      - JS_PORT=${JS_PORT}
    ports:      
      - "${NGINX_PORT}:80"    
    volumes:      
      - ./proxy/nginx.conf.template:/etc/nginx/nginx.conf.template    
      - ./proxy/nginx-entrypoint.sh:/usr/local/bin/nginx-entrypoint.sh
    entrypoint: ["/usr/local/bin/nginx-entrypoint.sh"]
    depends_on:      
      - node